name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build Java API
      run: ./mvnw clean package

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: path/to/your/frontend

    - name: Build React app
      run: npm run build
      working-directory: path/to/your/frontend

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/api:latest -f path/to/your/api/Dockerfile .
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/web:latest -f path/to/your/frontend/Dockerfile .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/api:latest
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/web:latest
